# Form implementation generated from reading ui file 'ui/login.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(970, 600)
        Form.resize(970,600)
        Form.setStyleSheet("QPushButton#pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11,131,120,219), stop:1 rgba(85,95,112,226));\n"
"    color: rgba(225,225,225);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150,123,111,219), stop:1 rgba(85,81,84,226));\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"\n"
"}")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 970, 600))
        self.widget.setStyleSheet("QPushButton#pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11,131,120,219), stop:1 rgba(85,95,112,226));\n"
"    color: rgba(225,225,225);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150,123,111,219), stop:1 rgba(85,81,84,226));\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.label_for_img = QtWidgets.QLabel(parent=self.widget)
        self.label_for_img.setGeometry(QtCore.QRect(0, 0, 600, 600))
        self.label_for_img.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"border-top-left-radius: 16px;\n"
"border-bottom-left-radius: 24px;")
        self.label_for_img.setText("")
        self.label_for_img.setObjectName("label_for_img")
        self.label_for_login = QtWidgets.QLabel(parent=self.widget)
        self.label_for_login.setGeometry(QtCore.QRect(584, 0, 386, 600))
        self.label_for_login.setStyleSheet("background-color: rgb(245, 245, 245); \n"
"border-radius:16px;\n"
"border-top-right-radius: 24px\n"
"")
        self.label_for_login.setText("")
        self.label_for_login.setObjectName("label_for_login")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(589, -40, 381, 641))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(40, 120, 40, 120)
        self.verticalLayout.setSpacing(40)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_for_title = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_for_title.setMinimumSize(QtCore.QSize(300, 40))
        self.label_for_title.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.label_for_title.setFont(font)
        self.label_for_title.setStyleSheet("")
        self.label_for_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_for_title.setObjectName("label_for_title")
        self.verticalLayout.addWidget(self.label_for_title)
        self.lineEdit_for_UID = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lineEdit_for_UID.setMinimumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_for_UID.setFont(font)
        self.lineEdit_for_UID.setStyleSheet("background-color: rgba(0,0,0,0 );\n"
"border: none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color: rgba(0,0,0,240);\n"
"padding-botton:7px;\n"
"")
        self.lineEdit_for_UID.setObjectName("lineEdit_for_UID")
        self.verticalLayout.addWidget(self.lineEdit_for_UID)
        self.lineEdit_for_password = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lineEdit_for_password.setMinimumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        self.lineEdit_for_password.setFont(font)
        self.lineEdit_for_password.setStyleSheet("background-color: rgba(0,0,0,0 );\n"
"border: none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color: rgba(0,0,0,240);\n"
"padding-botton:7px;\n"
"")
        self.lineEdit_for_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_for_password.setObjectName("lineEdit_for_password")
        self.verticalLayout.addWidget(self.lineEdit_for_password)
        self.pushButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(300, 48))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-radius:10px\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_for_title.setText(_translate("Form", "Login Account"))
        self.lineEdit_for_UID.setPlaceholderText(_translate("Form", "   User ID"))
        self.lineEdit_for_password.setPlaceholderText(_translate("Form", "   Password"))
        self.pushButton.setText(_translate("Form", "Log In"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
